### ISSUE TITLE
Op for prediction in CRF case

### ISSUE THREAD

**Issue by lminer** [guillaumegenthial/sequence_tagging#1]
Does it make sense to create an Op for the prediction part of the CRF model using something like `tf.py_func`? Would be nice to monitor accuracy during training. Or would that make training insanely slow?

**Comment by guillaumegenthial** [comment]
Considering the fact that an epoch is really fast (less than 2 minutes on GPU), I'm not sure that this is relevant as it would decrease the training speed! Plus the fact that you can monitor the accuracy at the end of each epoch. However, you can adapt the code and run the evaluation at the same time as you train, to get the accuracy. But it would make the code messier, and I think this is best to keep it as simple as possible so that people can adapt it easily to their needs.
