### ISSUE TITLE
Fine-tuning

### ISSUE THREAD

**Issue by grafael** [guillaumegenthial/sequence_tagging#22]
Hi Guilla, I'm trying to fine-tuning a previous model that I trained. After I load the weights I get an error (shapes mismatch). I saw in the code that the shapes are [None,None ...]. 
Should I reshape ( Will I lose information doing that? )
I just need to retrain the last layer everything else will work as feature extractor.

I appreciate any help on that.

**Comment by guillaumegenthial** [comment]
Hi,
I just pushed a new version with a new function in the base model `reinitialize_weights` that reinitializes the variables of a given scope. This should do what you want. (call it on the "proj" layer, like I wrote in `train.py`)
You shouldn't have shape mismatch. Check that you load the correct files and you haven't modified the graph you are trying to load.
Once you have reloaded your weights, you can also choose to add new parts of the graph (like a final layer with more items) but in that case, it should be a new element of the graph, with a different name and scope (otherwise tf.saver will try to load the model into this tensor and you'll get a shape mismatch). So if that's what you want to do, I advise you to create new elements of the graph. Consider also defining a new loss that only depends on the variables of the last layer.
Best,

Guillaume

**Comment by grafael** [comment]
Thanks Guillaume, was exactly what I needed.

Regards

Rafael
