### ISSUE TITLE
Purpose and logic behind `nsteps`

### ISSUE THREAD

**Issue by amundle-cs** [guillaumegenthial/sequence_tagging#26]
https://github.com/guillaumegenthial/sequence_tagging/blob/0e4e6a7e1bf87196714270a1dae8786ab2c487a8/model/ner_model.py#L179

I don't think I completely understand the purpose and logic behind extracting the `1th` dimension of the output. Help would be appreciated.

**Comment by guillaumegenthial** [comment]
I need to make a matmul. However, I think I need both entries to be matrices. That's why I reshape the output to be a 2d tensor. Then, I reshape it to the original shape, that's why I need to store the shape first. If you find a more clever way to do a general tensor multiplication, I would really much appreciate it, as it is a feature that would be useful... 

```
nsteps = tf.shape(output)[1]
output = tf.reshape(output, [-1, 2*
pred = tf.matmul(output, W) + b
self.logits = tf.reshape(pred, [-1, nsteps, self.config.ntags])
```
