### ISSUE TITLE
Initial value for word_embeddings

### ISSUE THREAD

**Issue by amundle-cs** [guillaumegenthial/sequence_tagging#31]
What would be a good value for `initializer` here:
https://github.com/guillaumegenthial/sequence_tagging/blob/0048d604f7a4e15037875593b331e1268ad6e887/model/ner_model.py#L106-L109

I have seen a `tf.random.uniform(...)` being used: http://www.wildml.com/2015/12/implementing-a-cnn-for-text-classification-in-tensorflow , but not much more than that.

**Comment by guillaumegenthial** [comment]
It seems like a standard way to initialize them with a random_uniform initializer
see also https://keras.io/layers/embeddings/
but I'm not sure about how much better it is supposed to be compared to the standard initializer.
I would go for random_uniform but between smaller values like sqrt(1/300) = 0.05 (so that your vectors have norm 1)

**Comment by guillaumegenthial** [comment]
closing the issue.
