### ISSUE TITLE
acc, F1 problem

### ISSUE THREAD

**Issue by diaoxue** [guillaumegenthial/sequence_tagging#34]
acc 28.23 - f1 9.78
- new best score!
Epoch 2 out of 15

the same data, use pytorch , F1 get 90+

B flag 2W 
I flag 6W 
O flag 100W

**Comment by diaoxue** [comment]
all the predict is O !

**Comment by guillaumegenthial** [comment]
Hi Diaoxue,
If you managed to learn with a similar model implemented in pytorch, it might be because something in the data pipeline is wrong. Also, you might have to wait a bit more, though such a low score is kind of surprising (based on what you say, a dummy algorithm giving 0 to everyone should get 90+ accuracy).
If you share some technical details here, I might be able to help you. Otherwise, if you have a working implementation in pytorch, I would recommand sticking to it.
-g

**Comment by guillaumegenthial** [comment]
any update?
otherwise closing the issue.
