### ISSUE TITLE
Add metrics to tensorboard

### ISSUE THREAD

**Issue by amundle-cs** [guillaumegenthial/sequence_tagging#37]
Hi @guillaumegenthial 
I have trying to re-architect some of this code to add the metrics to tensorboard, but falling short because it needs "fresh" minibatched data to compute the metrics. Do you think it is possible to add this operation to the computation graph or most likely not possible.

https://github.com/guillaumegenthial/sequence_tagging/blob/0048d604f7a4e15037875593b331e1268ad6e887/model/ner_model.py#L303

**Comment by guillaumegenthial** [comment]
Hi @amundle-cs 
That would be theoretically possible. 2 options:
1. you run the evalutation out of the graph (for F1 score and accuracy) and give it back as a placeholder that you can then send to tensorboard.
2. you use the latest version of the CRF (https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/contrib/crf/python/ops/crf.py) that runs in graph so that you can compute the accuracy directly in the graph. For the F1 score, I think you would have to go for option 1 anyway.
Note that adding these metrics to tensorboard will slow down learning and should be done just for the development phase, to check that your model is learning!
Hope that helps.

**Comment by guillaumegenthial** [comment]
Maybe having a look at https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/metrics/mean might help.
